In [ ]:
"""


Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.

"""

In [19]:
import numpy as np

In [9]:
def fibonacci_seq(num_first_terms):
    sequence = np.zeros(num_first_terms)
    sequence[0] = 1
    sequence[1] = 2
    
    for i in range(2,num_first_terms):
        sequence[i] = sequence[i-1] + sequence[i-2]
    
    return sequence

In [10]:
fibonacci_seq(10)

array([ 1.,  2.,  3.,  5.,  8., 13., 21., 34., 55., 89.])

In [12]:
four_million = 4e6

In [18]:
for i in range(10, 40):
    if fibonacci_seq(i)[-1] <= four_million:
        print('number of first terms {} does not exceed four million'.format(i))
    else:
        print('number of first terms {} does exceed four million'.format(i))

number of first terms 10 does not exceed four million
number of first terms 11 does not exceed four million
number of first terms 12 does not exceed four million
number of first terms 13 does not exceed four million
number of first terms 14 does not exceed four million
number of first terms 15 does not exceed four million
number of first terms 16 does not exceed four million
number of first terms 17 does not exceed four million
number of first terms 18 does not exceed four million
number of first terms 19 does not exceed four million
number of first terms 20 does not exceed four million
number of first terms 21 does not exceed four million
number of first terms 22 does not exceed four million
number of first terms 23 does not exceed four million
number of first terms 24 does not exceed four million
number of first terms 25 does not exceed four million
number of first terms 26 does not exceed four million
number of first terms 27 does not exceed four million
number of first terms 28 does not exceed four million
number of first terms 29 does not exceed four million
number of first terms 30 does not exceed four million
number of first terms 31 does not exceed four million
number of first terms 32 does not exceed four million
number of first terms 33 does exceed four million
number of first terms 34 does exceed four million
number of first terms 35 does exceed four million
number of first terms 36 does exceed four million
number of first terms 37 does exceed four million
number of first terms 38 does exceed four million
number of first terms 39 does exceed four million

In [21]:
fibonacci_seq(32)[-1]

3524578.0

In [23]:
fib = fibonacci_seq(32)

In [25]:
fib[fib%2==0].sum()

4613732.0